import mysql2 from 'mysql2'

export const majorsList = [
    "Accounting",
    "Accounting Technician",
    "Actuarial Science*",
    "Adult Development & Aging/Gerontology",
    "Advertising",
    "Aeronautical/Aerospace Engineering Technologies",
    "Aerospace/Aeronautical Engineering",
    "African American Studies",
    "Agribusiness Operations",
    "Agricultural Business & Management",
    "Agricultural Economics",
    "Agricultural Education",
    "Agricultural Mechanization",
    "Agricultural Production",
    "Agricultural/Bioengineering",
    "Agriculture, General",
    "Agronomy & Crop Science",
    "Aircraft Mechanics/Technology",
    "Aircraft Piloting & Navigation",
    "Alcohol/Drug Abuse Counseling",
    "American Indian/Native American Studies",
    "American/English Literature",
    "Animal Sciences",
    "Anthropology",
    "Applied Mathematics",
    "Architectural Drafting/CAD Technology",
    "Architectural Engineering",
    "Architectural Engineering Technology",
    "Architectural Environmental Design",
    "Architecture, General",
    "Area Studies, General (e.g., African, Middle Eastern)",
    "Art Education",
    "Art History, Criticism & Conservation",
    "Art, General",
    "Asian Area Studies",
    "Asian Languages & Literatures",
    "Astronomy",
    "Athletic Training",
    "Atmospheric Sciences & Meteorology",
    "Autobody Repair/Technology",
    "Automotive Engineering Technology",
    "Automotive Mechanics/Technology",
    "Aviation & Airway Science, General",
    "Aviation Management & Operations",
    "Avionics Technology",
    "Banking & Financial Support Services",
    "Bible/Biblical Studies",
    "Biochemistry & Biophysics",
    "Biology, General",
    "Biomedical Engineering",
    "Business Administration & Management, General",
    "Business Education",
    "Business/Management Quantitative Methods, General",
    "Business/Managerial Economics",
    "Career & Technical Education",
    "Cell/Cellular Biology",
    "Chemical Engineering",
    "Chemistry",
    "Child Care Services Management",
    "Child Development",
    "Chiropractic (Pre-Chiropractic)",
    "Cinema/Film",
    "Cinematography/Film/Vide Production",
    "City/Urban/Regional Planning",
    "Civil Engineering",
    "Civil Engineering Technology",
    "Classical/Ancient Languages & Literatures",
    "Communication Disorder Services (e.g., Speech Pathology)",
    "Communications Technology, General",
    "Communications, General",
    "Community Organization & Advocacy",
    "Comparative Literature",
    "Computer & Information Sciences, General",
    "Computer Engineering",
    "Computer Engineering Technology",
    "Computer Networking/Telecommunications",
    "Computer Science & Programming",
    "Computer Software & Media Applications",
    "Computer System Administration",
    "Construction Engineering/Management",
    "Construction Trades (e.g., carpentry, plumbing, electrical)",
    "Construction/Building Technology",
    "Consumer & Family Economics",
    "Corrections",
    "Cosmetology/Hairstyling*",
    "Counseling & Student Services",
    "Court Reporting*",
    "Creative Writing",
    "Criminal Justice",
    "Criminology",
    "Culinary Arts/Chef Training",
    "Curriculum & Instruction",
    "Dance",
    "Data Management Technology",
    "Dental Assisting",
    "Dental Hygiene",
    "Dentistry (Pre-Dentistry)",
    "Design & Visual Communications, General",
    "Diesel Mechanics/Technology",
    "Digital Communications/Media",
    "Divinity/Ministry",
    "Drafting/CAD Technology, General",
    "Early Childhood Education",
    "Ecology",
    "Economics",
    "Educational Administration",
    "Electrical, Electronics & Communications Engineering",
    "Electrical, Electronics Engineering Technologies",
    "Electrical/Electronics Equip Installation & Repair",
    "Electromechanical/Biomedical Engineering Technologies",
    "Elementary Education",
    "Emergency Medical Technology",
    "Engineering (Pre-Engineering), General",
    "Engineering Technology, General",
    "English Language & Literature, General",
    "English-as-a-Second-Language Education",
    "English/Language Arts Education",
    "Environmental Control Technologies",
    "Environmental Health Engineering",
    "Environmental Science",
    "Ethnic & Minority Studies, General",
    "European Area Studies",
    "Exercise Science/Physiology/Kinesiology",
    "Family & Consumer Sciences, General",
    "Fashion Merchandising",
    "Fashion/Apparel Design",
    "Finance, General",
    "Financial Planning & Services",
    "Fine/Studio Arts",
    "Fire Protection & Safety Technology",
    "Food & Nutrition",
    "Food Sciences & Technology",
    "Foreign Languages Education",
    "Foreign Languages/Literatures, General",
    "Forestry",
    "French Language & Literature",
    "Funeral Services & Mortuary Science",
    "Genetics",
    "Geography",
    "Geological & Earth Sciences",
    "German Language & Literature",
    "Graphic & Printing Equipment Operation*",
    "Graphic Design",
    "Health & Physical Education/Fitness",
    "Health Education",
    "Health Services Administration,General",
    "Health-Related Professions & Services, General*",
    "Health/Medical Technology, General",
    "Heating/Air Cond/Refrig Install/Repair",
    "History",
    "Horticulture Operations & Management",
    "Horticulture Science",
    "Hospital/Facilities Administration",
    "Hotel/Motel Management",
    "Human Resources Development/Training",
    "Human Resources Management",
    "Industrial Design",
    "Industrial Engineering",
    "Industrial Production Technologies",
    "Information Science",
    "Insurance & Risk Management",
    "Interior Architecture",
    "Interior Design",
    "International Business Management",
    "International Relations & Affairs",
    "Investments & Securities",
    "Journalism, Broadcast",
    "Journalism, Print",
    "Junior High/Middle School Education",
    "Labor/Industrial Relations",
    "Landscape Architecture",
    "Latin American Area Studies",
    "Latino/Chicano Studies",
    "Law (Pre-Law)",
    "Law Enforcement",
    "Legal Administrative Assisting/Secretarial*",
    "Legal Studies, General*",
    "Liberal Arts & General Studies*",
    "Library Science",
    "Linguistics",
    "Logistics & Materials Management",
    "Machine Tool Technology",
    "Management Information Systems",
    "Marine/Aquatic Biology",
    "Marketing Management & Research",
    "Mass Communications",
    "Massage Therapy",
    "Mathematics Education",
    "Mathematics, General",
    "Mechanical Drafting/CAD Technology",
    "Mechanical Engineering",
    "Mechanical Engineering Technology",
    "Mechanics & Repairers, General",
    "Medical Assisting",
    "Medical Laboratory Technology",
    "Medical Office/Secretarial",
    "Medical Radiologic Technology",
    "Medical Records",
    "Medical/Clinical Assisting, General",
    "Medicine (Pre-Medicine)",
    "Mental Health Counseling",
    "Microbiology & Immunology",
    "Middle Eastern Languages & Literatures",
    "Military Technologies*",
    "Multi/Interdisciplinary Studies*",
    "Multimedia/Animation/Special Effects",
    "Music Education",
    "Music, General",
    "Music, Performance",
    "Music, Theory & Composition",
    "Natural Resources Conservation, General",
    "Natural Resources Management",
    "North American Area Studies",
    "Nuclear Engineering",
    "Nuclear Medicine Technology",
    "Nursing, Practical/Vocational (LPN)",
    "Nursing, Registered (BS/RN)",
    "Occupational Therapy",
    "Occupational Therapy Assisting",
    "Office Supervision & Management",
    "Operations Management & Supervision",
    "Optometry (Pre-Optometry)",
    "Organizational Behavior",
    "Osteopathic Medicine",
    "Paralegal/Legal Assistant",
    "Parks, Recreation, & Leisure, General",
    "Parks/Rec/Leisure Facilities Management",
    "Personal Services, General*",
    "Pharmacy (Pre-Pharmacy)",
    "Philosophy",
    "Photography",
    "Physical Education & Coaching",
    "Physical Sciences, General",
    "Physical Therapy (Pre-Physical Therapy)",
    "Physical Therapy Assisting",
    "Physician Assisting",
    "Physics",
    "Political Science & Government",
    "Postsecondary Education",
    "Precision Production Trades, General",
    "Protective Services, General",
    "Psychiatric/Mental Health Technician",
    "Psychology, Clinical & Counseling",
    "Psychology, General",
    "Public Administration",
    "Public Administration & Services, General",
    "Public Affairs & Public Policy Analysis",
    "Public Health",
    "Public Relations & Organizational Communication",
    "Public Speaking",
    "Purchasing/Procurement/Contracts Management",
    "Quality Control & Safety Technologies",
    "Radio & Television Broadcasting",
    "Radio & Television Broadcasting Technology*",
    "Real Estate",
    "Rehabilitation Therapy",
    "Religion",
    "Religious Education",
    "Respiratory Therapy Technology",
    "Restaurant/Food Services Management",
    "Sales, Merchandising, & Marketing, General",
    "Science Education",
    "Secondary Education",
    "Secretarial Studies & Office Administration",
    "Small Business Management/Operations",
    "Social Sciences, General",
    "Social Studies/Sciences Education",
    "Social Work",
    "Sociology",
    "Spanish Language & Literature",
    "Special Education",
    "Sport & Fitness Administration/Management",
    "Statistics",
    "Surgical Technology",
    "Surveying Technology",
    "Teacher Assisting/Aide Education",
    "Teacher Education, General",
    "Teacher Education, Subject-Specific*",
    "Textile & Apparel",
    "Theatre Arts/Drama",
    "Theology, General",
    "Therapy & Rehabilitation, General",
    "Tourism & Travel Marketing",
    "Transportation & Materials Moving (e.g., air, ground, & marine)",
    "Travel/Tourism Management",
    "Urban Studies/Urban Affairs",
    "Veterinarian Assisting/Technology",
    "Veterinary Medicine (Pre-Veterinarian)",
    "Vocational Rehabilitation Counseling",
    "Webpage Design",
    "Welding Technology",
    "Wildlife & Wildlands Management",
    "Women’s Studies",
    "Zoology"
]

const connection = mysql2.createConnection({
    host: "localhost",
    user: "root",
    database: "coym"
})

export const createMajorsTable = function () {
    connection.connect(function (err: any) {
        if (err) throw err
        connection.query(`SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'coym'
            AND table_name = 'majors';`, function (err: any, result: any) {
            if (err) throw err
            if (!result.length) {
                connection.query(`CREATE TABLE IF NOT EXISTS majors (id INT AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (id)) `, function (err: any, result: any) {
                    if (err) throw err
                })
                for (var i = 0; i < majorsList.length; i++) {
                    connection.query(`INSERT INTO majors (name) VALUES ("${majorsList[i]}")`, function (err: any, result: any) {
                        if (err) throw err
                    })
                }
            }
        })
    })
}

export const getMajorList = function (res: any, req: any) {
    connection.connect(function (err: any) {
        if (err) throw err
        connection.query(`SELECT * FROM majors;`, function (err: any, result: any, fields: any) {
            if (err) throw err
            res.send({ status: true, message: result })
        })
    })
}